Add spanish translations
SymfonyCasts/reset-password-bundle pull request #157
Opened 2021-03-02 19:34 UTC by larzuk91

2021-03-03 09:14 UTC, bocharsky-bw requested changes
Ha, I can review in Spanish! Easy translation, well-known words :p 

P.S. One more repo, please! 😇  https://github.com/SymfonyCasts/verify-email-bundle

2021-03-03 09:14 UTC, bocharsky-bw commented on src/Resources/translations/ResetPasswordBundle.es.xlf
> +                <source>%count% año|%count% years</source>
```suggestion
                <source>%count% year|%count% years</source>
```

😉

2021-03-03 18:39 UTC, larzuk91 commented on src/Resources/translations/ResetPasswordBundle.es.xlf
> +                <source>%count% año|%count% years</source>
Wooooooooppps!!

2021-03-03 18:40 UTC, larzuk91 commented
Ha! Nice one Victor, your Spanish it's better than mine now!

2021-03-03 19:16 UTC, bocharsky-bw approved these changes
👍

2021-03-03 19:42 UTC, jrushlow approved these changes
Thanks @larzuk91

2021-03-04 14:10 UTC, weaverryan commented
Thanks Mr Diego!

2021-03-04 14:13 UTC, closed without merging