[translations] add additional Polish translations and fix pluralizations
SymfonyCasts/reset-password-bundle pull request #245
Opened 2022-09-22 13:57 UTC by Flower7C3

2022-09-23 15:52 UTC, bocharsky-bw requested changes
Thank you for fixing bad pluralization here and adding missing translations! The only comment I noticed that should be fixed before we could merge this

2022-09-23 15:52 UTC, bocharsky-bw commented on src/Resources/translations/ResetPasswordBundle.pl.xlf
> +    <file original="file.ext" source-language="pl" target-language="pl" datatype="plaintext">
This line should be reverted, the source language is `en` indeed

2022-09-23 15:58 UTC, bocharsky-bw commented
@Flower7C3 P.S. If you have time, please, take a look at another bundle that also misses some Polish translations: https://github.com/SymfonyCasts/verify-email-bundle/blob/main/src/Resources/translations/VerifyEmailBundle.pl.xlf 

It would be great to add missing translations there too :)

2022-09-23 16:04 UTC, Flower7C3 commented
Source language fixed.

2022-09-23 16:18 UTC, bocharsky-bw approved these changes
Dziękuje bardzo!

2022-09-27 06:10 UTC, jrushlow approved these changes
Thanks for the updates @Flower7C3 !

2022-09-27 06:10 UTC, merged